GET http://localhost:3000/contact
    ?email=example@gmail.com

###

POST http://localhost:3000/contact HTTP/1.1
content-type: application/json

{
    "name": "Mark Luke",
    "number": "09086748574"
}

    